name: Publish package to GitHub Packages
on:
  push:
    branches:
      - 'dev/0.6-forge'
      - 'dev/0.7-forge'
      - 'dev/0.8'
      - 'dev/0.9'
      - 'dev/0.10.0'
      - 'dev/0.11.0'
      - 'dev/0.12.0'
      - 'dev/1.0'
      - 'dev/1.1'
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Publish package
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}