name: Java CI

on:
  push:
    branches:
      - 'dev/1.2'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Upload to Local Maven
        run: ./gradlew publish --stacktrace
      - name: Upload artifacts (Pre-Publish)
        uses: actions/upload-artifact@v4
        with:
          name: pre-publish
          path: ${{ github.workspace }}/build/repo
